version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: whaticket_postgres
    environment:
      POSTGRES_DB: whaticket
      POSTGRES_USER: whaticket
      POSTGRES_PASSWORD: whaticket123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: whaticket_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

  mailhog:
    image: mailhog/mailhog
    container_name: whaticket_mailhog
    ports:
      - "1025:1025" # SMTP server
      - "8025:8025" # Web UI
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
