services:
  - type: web
    name: simao-ia-rural-backend
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python src/main.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: simao-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: FRONTEND_URL
        value: https://simao-ia-rural-frontend.onrender.com

databases:
  - name: simao-db
    plan: starter

